version: '3'

services:
  ct-launch:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cloudlet_default

networks:
  cloudlet_default:
    driver: bridge
  
